server:
  port: 8002

spring:
  application:
    name: short-link-project
  mvc:
    view:
      prefix: /templates/
      suffix: .html

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

logging:
  pattern:
    level: debug
  config: classpath:logback-spring.xml