spring:
  datasource:
    username: root
    password: fengyan1
    url: jdbc:mysql://127.0.0.1:3306/shortlink?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: select 1
      connection-timeout: 20000
      idle-timeout: 300000
      maximum-pool-size: 5
      minimum-idle: 5
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: fengyan1

server:
  port: 8080

# springdoc-openapi项目配置
springdoc:
  group-configs:
    - group: 后端管理接口
      packages-to-scan: com.fengrui.shortlink.admin.controller

# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh-CN



logging:
  pattern:
    level: debug
  config: classpath:logback-spring.xml
