spring:
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: fengyan1

server:
  port: 8080

# springdoc-openapi项目配置
springdoc:
  group-configs:
    - group: 后端管理接口
      packages-to-scan: com.fengrui.shortlink.admin.controller

# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh-CN

short-link:
  group:
    max-num: 20

logging:
  pattern:
    level: debug
  config: classpath:logback-spring.xml
